* harmony

harmony is a load balancing server that distribute request based on the basic
round robin scheduling algorithm

**** Made with love using BABASHKA

Solution to - https://codingchallenges.fyi/challenges/challenge-load-balancer/


** Goals

    Build a load balancer that can send traffic to two or more servers.
    Health check the servers.
    Handle a server going offline (failing a health check).
    Handle a server coming back online (passing a health check).


** Usage

Start the load balancing server:

#+BEGIN_SRC bash
  ./src/harmony/load_balancer.bb
#+End_SRC

This will start the load balancing server on port 80 by default

Now, start multiple backend server on port : 1010, 1011, 1012 and 1013

#+BEGIN_SRC bash
  ./src/harmony/be.bb <port-number>
#+End_SRC

NOTE: Currently load balancing server only checks and distribute request
to backend servers running on port 1010, 1011, 1012, and 1013. This can
be changed to make it dynmaic in the future.

Make GET request on host: `127.0.0.1` and port `80`.

#+BEGIN_SRC bash
  curl http://localhost:80
#+end_src


The load balancer will now distribute the request each of these server
using round robin algorithm
